# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 214)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnClickMe = QtWidgets.QPushButton(self.centralwidget)
        self.btnClickMe.setGeometry(QtCore.QRect(20, 120, 75, 25))
        self.btnClickMe.setMinimumSize(QtCore.QSize(75, 25))
        self.btnClickMe.setObjectName("btnClickMe")
        self.lineEditNaam = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNaam.setGeometry(QtCore.QRect(70, 20, 191, 27))
        self.lineEditNaam.setMinimumSize(QtCore.QSize(191, 27))
        self.lineEditNaam.setObjectName("lineEditNaam")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 60, 191, 27))
        self.label.setMinimumSize(QtCore.QSize(191, 27))
        self.label.setText("")
        self.label.setObjectName("label")
        self.btnClearText = QtWidgets.QPushButton(self.centralwidget)
        self.btnClearText.setGeometry(QtCore.QRect(120, 120, 75, 25))
        self.btnClearText.setMinimumSize(QtCore.QSize(75, 25))
        self.btnClearText.setObjectName("btnClearText")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(220, 120, 75, 25))
        self.btnClose.setMinimumSize(QtCore.QSize(75, 25))
        self.btnClose.setObjectName("btnClose")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnClickMe.setText(_translate("MainWindow", "Click Me"))
        self.lineEditNaam.setPlaceholderText(_translate("MainWindow", "Enter your name"))
        self.btnClearText.setText(_translate("MainWindow", "Clear"))
        self.btnClose.setText(_translate("MainWindow", "Close"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
